table sentiment_test_results
	lineageTag: c1a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5c6

	measure 'Total Predictions' = ```
			COUNTROWS('sentiment_test_results')
			
			```
		formatString: 0
		lineageTag: d1a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5c7

	measure 'Correct Predictions' = ```
			
			COUNTROWS(
			    FILTER(
			        'sentiment_test_results',
			        'sentiment_test_results'[actual_sentiment] = 'sentiment_test_results'[predicted_sentiment]
			    )
			)
			
			```
		formatString: 0
		lineageTag: d2a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5c8

	measure 'Incorrect Predictions' = [Total Predictions] - [Correct Predictions]
		formatString: 0
		lineageTag: d3a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5c9

	measure Accuracy = ```
			
			DIVIDE(
			    [Correct Predictions],
			    [Total Predictions],
			    0
			)
			
			```
		formatString: 0.00%
		lineageTag: d4a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5d0

	measure 'True Positives' =
			
			VAR SelectedClass = SELECTEDVALUE(sentiment_test_results[actual_sentiment])
			RETURN
			COUNTROWS(
			    FILTER(
			        sentiment_test_results,
			        sentiment_test_results[actual_sentiment] = SelectedClass &&
			        sentiment_test_results[predicted_sentiment] = SelectedClass
			    )
			)
		formatString: 0
		lineageTag: d5a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5d1

	measure 'False Positives' =
			
			VAR SelectedClass = SELECTEDVALUE('sentiment_test_results'[predicted_sentiment])
			RETURN
			COUNTROWS(
			    FILTER(
			        'sentiment_test_results',
			        'sentiment_test_results'[predicted_sentiment] = SelectedClass &&
			        'sentiment_test_results'[actual_sentiment] <> SelectedClass
			    )
			)
		formatString: 0
		lineageTag: d6a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5d2

	measure 'False Negatives' = ```
			
			VAR SelectedClass = SELECTEDVALUE('sentiment_test_results'[actual_sentiment])
			RETURN
			COUNTROWS(
			    FILTER(
			        'sentiment_test_results',
			        'sentiment_test_results'[actual_sentiment] = SelectedClass &&
			        'sentiment_test_results'[predicted_sentiment] <> SelectedClass
			    )
			)
			
			```
		formatString: 0
		lineageTag: d7a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5d3

	measure 'Macro Precision' = ```
			
			VAR ClassTable = DISTINCT(sentiment_test_results[actual_sentiment])
			VAR NumClasses = COUNTROWS(ClassTable)
			VAR PrecisionSum =
			    SUMX(
			        ClassTable,
			        VAR CurrentClass = sentiment_test_results[actual_sentiment]
			        VAR TP = CALCULATE(
			            COUNTROWS(sentiment_test_results),
			            sentiment_test_results[actual_sentiment] = CurrentClass,
			            sentiment_test_results[predicted_sentiment] = CurrentClass
			        )
			        VAR FP = CALCULATE(
			            COUNTROWS(sentiment_test_results),
			            sentiment_test_results[predicted_sentiment] = CurrentClass,
			            sentiment_test_results[actual_sentiment] <> CurrentClass
			        )
			        RETURN DIVIDE(TP, TP + FP, 0)
			    )
			RETURN
			DIVIDE(PrecisionSum, NumClasses, 0)
			
			```
		formatString: 0.00%
		lineageTag: d8a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5d4

	measure 'Macro Recall' =
			
			VAR ClassTable = DISTINCT(sentiment_test_results[actual_sentiment])
			VAR NumClasses = COUNTROWS(ClassTable)
			VAR RecallSum =
			    SUMX(
			        ClassTable,
			        VAR CurrentClass = sentiment_test_results[actual_sentiment]
			        VAR TP = CALCULATE(
			            COUNTROWS(sentiment_test_results),
			            sentiment_test_results[actual_sentiment] = CurrentClass,
			            sentiment_test_results[predicted_sentiment] = CurrentClass
			        )
			        VAR F_N = CALCULATE(
			            COUNTROWS(sentiment_test_results),
			            sentiment_test_results[actual_sentiment] = CurrentClass,
			            sentiment_test_results[predicted_sentiment] <> CurrentClass
			        )
			        RETURN DIVIDE(TP, TP + F_N, 0)
			    )
			RETURN
			DIVIDE(RecallSum, NumClasses, 0)
		formatString: 0.00%
		lineageTag: d9a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5d5

	measure 'Macro F1 Score' =
			
			VAR P = [Macro Precision]
			VAR R = [Macro Recall]
			RETURN
			DIVIDE(2 * P * R, P + R, 0)
		formatString: 0.00%
		lineageTag: e0a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5d6

	measure 'CM Count' =
			
			VAR ActualClass = SELECTEDVALUE(sentiment_test_results[actual_sentiment])
			VAR PredictedClass = SELECTEDVALUE(sentiment_test_results[predicted_sentiment])
			RETURN
			0 + COUNTROWS(
			    FILTER(
			        ALL(sentiment_test_results),
			        sentiment_test_results[actual_sentiment] = ActualClass &&
			        sentiment_test_results[predicted_sentiment] = PredictedClass
			    )
			)
		formatString: 0
		lineageTag: e1a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5d7

	measure 'Class Precision' =
			
			VAR CurrentClass = SELECTEDVALUE(sentiment_test_results[actual_sentiment])
			VAR TP = CALCULATE(
			    COUNTROWS(sentiment_test_results),
			    ALLEXCEPT(sentiment_test_results, sentiment_test_results[actual_sentiment]),
			    sentiment_test_results[predicted_sentiment] = CurrentClass
			)
			VAR AllPredictedAsClass = CALCULATE(
			    COUNTROWS(sentiment_test_results),
			    ALL(sentiment_test_results),
			    sentiment_test_results[predicted_sentiment] = CurrentClass
			)
			RETURN
			IF(ISBLANK(CurrentClass), BLANK(), DIVIDE(TP, AllPredictedAsClass, 0))
		formatString: 0.00%
		lineageTag: e2a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5d8

	measure 'Class Recall' =
			
			VAR CurrentClass = SELECTEDVALUE(sentiment_test_results[actual_sentiment])
			VAR TP = CALCULATE(
			    COUNTROWS(sentiment_test_results),
			    ALLEXCEPT(sentiment_test_results, sentiment_test_results[actual_sentiment]),
			    sentiment_test_results[predicted_sentiment] = CurrentClass
			)
			VAR AllActualClass = CALCULATE(
			    COUNTROWS(sentiment_test_results),
			    ALLEXCEPT(sentiment_test_results, sentiment_test_results[actual_sentiment])
			)
			RETURN
			IF(ISBLANK(CurrentClass), BLANK(), DIVIDE(TP, AllActualClass, 0))
		formatString: 0.00%
		lineageTag: e3a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5d9

	measure 'Class F1 Score' =
			
			VAR P = [Class Precision]
			VAR R = [Class Recall]
			RETURN
			IF(ISBLANK(P) || ISBLANK(R), BLANK(), DIVIDE(2 * P * R, P + R, 0))
		formatString: 0.00%
		lineageTag: e4a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5e0

	measure 'Avg Confidence' = ```
			
			AVERAGE('sentiment_test_results'[confidence_score])
			
			```
		lineageTag: e5a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5e1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column text
		dataType: string
		lineageTag: f1a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5e2
		summarizeBy: none
		sourceColumn: text

		annotation SummarizationSetBy = Automatic

	column actual_sentiment
		dataType: string
		lineageTag: f2a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5e3
		summarizeBy: none
		sourceColumn: actual_sentiment

		annotation SummarizationSetBy = Automatic

	column predicted_sentiment
		dataType: string
		lineageTag: f3a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5e4
		summarizeBy: none
		sourceColumn: predicted_sentiment

		annotation SummarizationSetBy = Automatic

	column confidence_score
		dataType: double
		lineageTag: f4a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5e5
		summarizeBy: average
		sourceColumn: confidence_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column prediction_date
		dataType: dateTime
		formatString: General Date
		lineageTag: f5a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5e6
		summarizeBy: none
		sourceColumn: prediction_date

		annotation SummarizationSetBy = Automatic

	column Year = YEAR('sentiment_test_results'[prediction_date])
		dataType: int64
		formatString: 0
		lineageTag: f6a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5e7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Month = MONTH('sentiment_test_results'[prediction_date])
		dataType: int64
		formatString: 0
		lineageTag: f7a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5e8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Day = DAY('sentiment_test_results'[prediction_date])
		dataType: int64
		formatString: 0
		lineageTag: f8a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5e9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Hour = HOUR('sentiment_test_results'[prediction_date])
		dataType: int64
		formatString: 0
		lineageTag: f9a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5f0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: a0b1c2d3-e4f5-a6b7-c8d9-e0f1a2b3c4d5

		level Year
			lineageTag: a1b1c2d3-e4f5-a6b7-c8d9-e0f1a2b3c4d6
			column: Year

		level Month
			lineageTag: a2b1c2d3-e4f5-a6b7-c8d9-e0f1a2b3c4d7
			column: Month

		level Day
			lineageTag: a3b1c2d3-e4f5-a6b7-c8d9-e0f1a2b3c4d8
			column: Day

		level Hour
			lineageTag: a4b1c2d3-e4f5-a6b7-c8d9-e0f1a2b3c4d9
			column: Hour

	partition sentiment_test_results = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\pmkul\Downloads\ml-eval-powerbi\data\sentiment_test_results.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"text", type text}, {"actual_sentiment", type text}, {"predicted_sentiment", type text}, {"confidence_score", type number}, {"prediction_date", type datetime}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

