table iris_test_results
	lineageTag: bb4815fc-f1aa-45a3-8437-7dffd5d8b414

	measure 'Total Predictions' = ```
			COUNTROWS('iris_test_results')
			
			```
		formatString: 0
		lineageTag: 787b45fc-5eb9-4dd5-aba8-cf66ea44b8b1

	measure 'Correct Predictions' = ```
			
			COUNTROWS(
			    FILTER(
			        'iris_test_results',
			        'iris_test_results'[actual_species] = 'iris_test_results'[predicted_species]
			    )
			)
			
			```
		formatString: 0
		lineageTag: 80fda4e3-5748-486a-a091-fb365245159b

	measure 'Incorrect Predictions' = [Total Predictions] - [Correct Predictions]
		formatString: 0
		lineageTag: 938be84e-4182-4f8f-acec-54b6ede5a91c

	measure Accuracy = ```
			
			DIVIDE(
			    [Correct Predictions],
			    [Total Predictions],
			    0
			)
			
			```
		formatString: 0.00%
		lineageTag: aedbe163-3bfc-4f7d-aad4-75a6bd3a0d92

	measure 'True Positives' =
			
			VAR SelectedClass = SELECTEDVALUE(iris_test_results[actual_species])
			RETURN
			COUNTROWS(
			    FILTER(
			        iris_test_results,
			        iris_test_results[actual_species] = SelectedClass &&
			        iris_test_results[predicted_species] = SelectedClass
			    )
			)
		formatString: 0
		lineageTag: 1b745107-1de6-4ab6-bbf4-e44a203d962c

	measure 'False Positives' =
			
			VAR SelectedClass = SELECTEDVALUE('iris_test_results'[predicted_species])
			RETURN
			COUNTROWS(
			    FILTER(
			        'iris_test_results',
			        'iris_test_results'[predicted_species] = SelectedClass &&
			        'iris_test_results'[actual_species] <> SelectedClass
			    )
			)
		formatString: 0
		lineageTag: 014d4f26-17eb-4605-9fb6-ff5c811b8e87

	measure 'False Negatives' = ```
			
			VAR SelectedClass = SELECTEDVALUE('iris_test_results'[actual_species])
			RETURN
			COUNTROWS(
			    FILTER(
			        'iris_test_results',
			        'iris_test_results'[actual_species] = SelectedClass &&
			        'iris_test_results'[predicted_species] <> SelectedClass
			    )
			)
			
			```
		formatString: 0
		lineageTag: b547901f-f57f-4203-8536-51349ba2caf8

	measure 'Macro Precision' = ```
			
			VAR ClassTable = DISTINCT(iris_test_results[actual_species])
			VAR NumClasses = COUNTROWS(ClassTable)
			VAR PrecisionSum = 
			    SUMX(
			        ClassTable,
			        VAR CurrentClass = iris_test_results[actual_species]
			        VAR TP = CALCULATE(
			            COUNTROWS(iris_test_results),
			            iris_test_results[actual_species] = CurrentClass,
			            iris_test_results[predicted_species] = CurrentClass
			        )
			        VAR FP = CALCULATE(
			            COUNTROWS(iris_test_results),
			            iris_test_results[predicted_species] = CurrentClass,
			            iris_test_results[actual_species] <> CurrentClass
			        )
			        RETURN DIVIDE(TP, TP + FP, 0)
			    )
			RETURN
			DIVIDE(PrecisionSum, NumClasses, 0)
			
			```
		formatString: 0.00%
		lineageTag: 1566eb4a-4704-42ba-a838-6b61cba49a7d

	measure 'Macro Recall' = ```
			
			VAR ClassTable = DISTINCT(iris_test_results[actual_species])
			VAR NumClasses = COUNTROWS(ClassTable)
			VAR RecallSum = 
			    SUMX(
			        ClassTable,
			        VAR CurrentClass = iris_test_results[actual_species]
			        VAR TP = CALCULATE(
			            COUNTROWS(iris_test_results),
			            iris_test_results[actual_species] = CurrentClass,
			            iris_test_results[predicted_species] = CurrentClass
			        )
			        VAR F_N = CALCULATE(
			            COUNTROWS(iris_test_results),
			            iris_test_results[actual_species] = CurrentClass,
			            iris_test_results[predicted_species] <> CurrentClass
			        )
			        RETURN DIVIDE(TP, TP + F_N, 0)
			    )
			RETURN
			DIVIDE(RecallSum, NumClasses, 0)
			```
		formatString: 0.00%
		lineageTag: 6a37ef97-5199-490e-bb96-7ec2830a3097

	measure 'F1 Score' =
			
			DIVIDE(
			    2 * [Macro Precision] * [Macro Recall],
			    [Macro Precision] + [Macro Recall],
			    0
			)
		formatString: 0.00%
		lineageTag: 91fe3d1e-a00c-4dc9-916f-425fb1c81626

	measure 'CM Count' =
			
			VAR ActualClass = SELECTEDVALUE(iris_test_results[actual_species])
			VAR PredictedClass = SELECTEDVALUE(iris_test_results[predicted_species])
			RETURN
			COUNTROWS(
			    FILTER(
			        ALL(iris_test_results),
			        iris_test_results[actual_species] = ActualClass &&
			        iris_test_results[predicted_species] = PredictedClass
			    )
			)
		formatString: 0
		lineageTag: 98781b23-0ed1-42ac-9ac3-c582ec20317d

	measure 'Class Precision' =
			
			VAR CurrentClass = SELECTEDVALUE(iris_test_results[actual_species])
			VAR TP = CALCULATE(
			    COUNTROWS(iris_test_results),
			    ALLEXCEPT(iris_test_results, iris_test_results[actual_species]),
			    iris_test_results[predicted_species] = CurrentClass
			)
			VAR AllPredictedAsClass = CALCULATE(
			    COUNTROWS(iris_test_results),
			    ALL(iris_test_results),
			    iris_test_results[predicted_species] = CurrentClass
			)
			RETURN
			IF(ISBLANK(CurrentClass), BLANK(), DIVIDE(TP, AllPredictedAsClass, 0))
		formatString: 0.00%
		lineageTag: 67213dee-b481-4213-9169-10bb4aa44978

	measure 'Macro F1 Score' =
			
			VAR P = [Macro Precision]
			VAR R = [Macro Recall]
			RETURN
			DIVIDE(2 * P * R, P + R, 0)
		formatString: 0.00%
		lineageTag: 2a770774-8bdd-4ca3-806f-829b47b4c9c9

	measure 'Class Recall' =
			
			VAR CurrentClass = SELECTEDVALUE(iris_test_results[actual_species])
			VAR TP = CALCULATE(
			    COUNTROWS(iris_test_results),
			    ALLEXCEPT(iris_test_results, iris_test_results[actual_species]),
			    iris_test_results[predicted_species] = CurrentClass
			)
			VAR AllActualClass = CALCULATE(
			    COUNTROWS(iris_test_results),
			    ALLEXCEPT(iris_test_results, iris_test_results[actual_species])
			)
			RETURN
			IF(ISBLANK(CurrentClass), BLANK(), DIVIDE(TP, AllActualClass, 0))
		formatString: 0.00%
		lineageTag: 9ed4da4a-97f1-4016-ac8f-a074ee88f099

	measure 'Class F1 Score' =
			
			VAR P = [Class Precision]
			VAR R = [Class Recall]
			RETURN
			IF(ISBLANK(P) || ISBLANK(R), BLANK(), DIVIDE(2 * P * R, P + R, 0))
		formatString: 0.00%
		lineageTag: fe806c1d-c97f-458a-ba18-19e022c879f5

	column 'sepal length (cm)'
		dataType: double
		lineageTag: 0a984eda-efd8-4106-b850-c6e3d5a6c08e
		summarizeBy: sum
		sourceColumn: sepal length (cm)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'sepal width (cm)'
		dataType: double
		lineageTag: c27df08c-aceb-4458-9ba5-8ce41d878b2f
		summarizeBy: sum
		sourceColumn: sepal width (cm)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'petal length (cm)'
		dataType: double
		lineageTag: 04cbb051-bcee-472c-ad08-21515b3a87cb
		summarizeBy: sum
		sourceColumn: petal length (cm)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'petal width (cm)'
		dataType: double
		lineageTag: 90bd68c3-bd82-4ad3-9890-870731a85cee
		summarizeBy: sum
		sourceColumn: petal width (cm)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column actual_label
		dataType: int64
		formatString: 0
		lineageTag: 1326ea0e-9919-4899-94b0-a0b25c14f067
		summarizeBy: sum
		sourceColumn: actual_label

		annotation SummarizationSetBy = Automatic

	column actual_species
		dataType: string
		lineageTag: 847b5bc2-9a44-428f-ac14-3e52a10ffcbe
		summarizeBy: none
		sourceColumn: actual_species

		annotation SummarizationSetBy = Automatic

	column predicted_label
		dataType: int64
		formatString: 0
		lineageTag: 10d8d5ba-73da-4d83-8e47-db4be5ee9701
		summarizeBy: sum
		sourceColumn: predicted_label

		annotation SummarizationSetBy = Automatic

	column predicted_species
		dataType: string
		lineageTag: a228ace3-e584-4602-aac5-f802f1e9c392
		summarizeBy: none
		sourceColumn: predicted_species

		annotation SummarizationSetBy = Automatic

	partition iris_test_results = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\pmkul\Downloads\ml-eval-powerbi\data\iris_test_results.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sepal length (cm)", type number}, {"sepal width (cm)", type number}, {"petal length (cm)", type number}, {"petal width (cm)", type number}, {"actual_label", Int64.Type}, {"actual_species", type text}, {"predicted_label", Int64.Type}, {"predicted_species", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

